### ISSUE TITLE
RegistryCI and TagBot

### ISSUE THREAD

**Issue by AntonOresten** [MurrellGroup/MurrellGroupRegistry#1]
See https://juliaregistries.github.io/RegistryCI.jl

TagBot would make it slightly less annoying to create new versions.

**Comment by AntonOresten** [comment]
Packages using the MurrellGroupRegistry are advised to [add the custom registry](https://github.com/JuliaRegistries/TagBot?tab=readme-ov-file#custom-registries) to their `.github/workflows/TagBot.yml` for automatic tagging upon registration:
```yaml
with:
  token: ${{ secrets.GITHUB_TOKEN }}
  registry: MurrellGroup/MurrellGroupRegistry
```
